# Generated by Django 2.1.7 on 2019-03-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtimple', '0003_moduleaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModuleAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn_module_actions', related_query_name='rqn_module_action', to='jwtimple.ModuleAction')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_actions', related_query_name='role_action', to='jwtimple.Role')),
            ],
            options={
                'db_table': 'role_module_actions',
            },
        ),
    ]
